<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="interventions" nsURI="http:///org/eclipse/stem/interventions.ecore"
    nsPrefix="org.eclipse.stem.interventions">
  <eClassifiers xsi:type="ecore:EClass" name="InterventionLabel" abstract="true" eSuperTypes="../../org.eclipse.stem.core/model/graph.ecore#//StaticNodeLabel"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardInterventionLabel" eSuperTypes="#//InterventionLabel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationIdentifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="human"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlGraphGenerator" eSuperTypes="../../org.eclipse.stem.graphgenerators/model/graphgenerators.ecore#//GraphGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vaccinationFraction" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isolationFraction" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationIdentifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="human"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType ../../org.eclipse.stem.core/model/common.ecore#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterventionLabelValue" abstract="true"
      eSuperTypes="../../org.eclipse.stem.core/model/graph.ecore#//LabelValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardInterventionLabelValue" eSuperTypes="#//InterventionLabelValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vaccinations" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isolations" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardPeriodicInterventionLabelValue"
      eSuperTypes="#//InterventionLabelValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absolute" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="86400000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vaccinations" unique="false"
        upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isolations" unique="false"
        upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicControlGraphGenerator" eSuperTypes="../../org.eclipse.stem.graphgenerators/model/graphgenerators.ecore#//GraphGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationIdentifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="human"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataPath" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"
        defaultValueLiteral="86400000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useVaccinations" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
</ecore:EPackage>
