<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stochastic" nsURI="http:///org/eclipse/stem/solvers/stochastic"
    nsPrefix="org.eclipse.stem.solvers.stochastic">
  <eClassifiers xsi:type="ecore:EClass" name="Stochastic" eSuperTypes="../../org.eclipse.stem.core/model/solver.ecore#//Solver"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardStochastic" eSuperTypes="#//Stochastic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seed" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"
        defaultValueLiteral="17"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RandomizeSeed" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
