/*
 * generated by Xtext
 */
package org.eclipse.stem.model.ctdl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.stem.model.ctdl.ui.internal.CTDLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CTDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CTDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CTDLActivator.getInstance().getInjector(CTDLActivator.ORG_ECLIPSE_STEM_MODEL_CTDL_CTDL);
	}
	
}
