/*******************************************************************************
 * Copyright (c) 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018
 * IBM Corporation, BfR, and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation and new features
 *     Bundesinstitut für Risikobewertung - Pajek Graph interface, new Veterinary Models
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.stem.model.ctdl;

import org.eclipse.stem.model.ctdl.scoping.MetamodelContextLinker;
import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.resource.XtextResource;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CTDLRuntimeModule extends org.eclipse.stem.model.ctdl.AbstractCTDLRuntimeModule {

	// contributed by org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
	@Override
	public Class<? extends org.eclipse.xtext.resource.IContainer.Manager> bindIContainer$Manager() {
		return org.eclipse.xtext.resource.impl.SimpleResourceDescriptionsBasedContainerManager.class;
	}

	
	@Override
	public Class<? extends ILinkingService> bindILinkingService() {
		return MetamodelContextLinker.class;
	}
	
	@Override
	public Class<? extends XtextResource> bindXtextResource() {
		return ContextSensitiveResourceWrapper.class;
	}
}
