/*
* generated by Xtext
*/
package org.eclipse.stem.model.ctdl.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractCTDLJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipse.stem.model.ctdl.ctdl.CtdlPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http:///org/eclipse/stem/model/metamodel.ecore"));
		return result;
	}

}
