<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evolvingcrossspeciesmodel" nsURI="http:///org/eclipse/stem/evolvingcrossspeciesmodel/evolvingcrossspeciesmodel.ecore"
    nsPrefix="org.eclipse.stem.evolvingcrossspeciesmodel">
  <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
    <details key="version" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/stem/modelgen/metamodel">
    <details key="uri" value="platform:/resource/.stemgenerator/model/evolvingcrossspeciesmodel.metamodel"/>
  </eAnnotations>
  <eAnnotations source="http:///org/eclipse/stem/modelgen/metamodel">
    <details key="uri" value="platform:/resource/org.eclipse.stem.evolvingcrossspeciesmodel/model/evolvingcrossspeciesmodel.metamodel"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EvolvingCrossSpeciesModelLabel" eSuperTypes="platform:/plugin/org.eclipse.stem.diseasemodels/model/standard.ecore#//StandardDiseaseModelLabel">
    <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
      <details key="version" value="1.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvolvingCrossSpeciesModelLabelValue"
      eSuperTypes="platform:/plugin/org.eclipse.stem.diseasemodels/model/standard.ecore#//SIRLabelValue">
    <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
      <details key="version" value="1.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="e" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvolvingCrossSpeciesModel" eSuperTypes="platform:/plugin/org.eclipse.stem.diseasemodels.evolving/model/evolving.ecore#//EvolvingSIRDiseaseModel">
    <eAnnotations source="http:///org/eclipse/stem/modelgen/model/label">
      <details key="*" value="EvolvingCrossSpeciesModelLabel"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/stem/modelgen/model/labelvalue">
      <details key="*" value="EvolvingCrossSpeciesModelLabelValue"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/stem/modelgen/model/adapters"/>
    <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
      <details key="version" value="1.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherToOtherTransmissionRate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/modelparam/messages">
        <details key="name" value="Other To Other Transmission Rate"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherRecoveryRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.1">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/modelparam/messages">
        <details key="name" value="Other Recovery Rate"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherToHostTransmissionRate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/modelparam/messages">
        <details key="name" value="Other To Host Transmission Rate"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatureFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="20.0">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/modelparam/messages">
        <details key="name" value="Temperature Factor"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherPopulationIdentifier"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="avian">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/modelparam/messages">
        <details key="name" value="Other Population Identifier"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherImmunityLossRate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.001">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/modelparam/messages">
        <details key="name" value="Other Immunity Loss Rate"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incubationRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0">
      <eAnnotations source="http:///org/eclipse/stem/modelgen/modelparam/messages">
        <details key="name" value="Incubation Rate"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/stem/modelgen/generated">
        <details key="version" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
