/*
* generated by Xtext
*/
package org.eclipse.stem.model.ctdl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CTDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/stem/model/ctdl/parser/antlr/internal/InternalCTDL.tokens");
	}
}
