/*
* generated by Xtext
*/
package org.eclipse.stem.model.ctdl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.stem.model.ctdl.services.CTDLGrammarAccess;

public class CTDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CTDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.stem.model.ctdl.parser.antlr.internal.InternalCTDLParser createParser(XtextTokenStream stream) {
		return new org.eclipse.stem.model.ctdl.parser.antlr.internal.InternalCTDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CompartmentTransitionDefinitions";
	}
	
	public CTDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CTDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
